sudo: required
services:
  - docker

before_install:
  - docker build -t moussavdb/build-node:latest -t moussavdb/build-node:build_$TRAVIS_BUILD_NUMBER .
script:
  - docker images moussavdb/build-node
  
after_success:
  - docker login -u="moussavdb" -p="$DOCKER_PASSWORD";
    docker push moussavdb/build-node:latest;
    docker push moussavdb/build-node:build_$TRAVIS_BUILD_NUMBER;
