sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t moussavdb/build-nodejs:latest -t moussavdb/build-nodejs:build_$TRAVIS_BUILD_NUMBER .
script:
  - docker images moussavdb/build-nodejs
  
after_success:
  - docker login -u="moussavdb" -p="$DOCKER_PASSWORD";
    docker push moussavdb/build-nodejs:latest;
    docker push moussavdb/build-nodejs:build_$TRAVIS_BUILD_NUMBER;
