arch:
  - amd64
  - arm64
os: linux
dist: focal

language: generic

services:
  - docker

before_install:
  - docker build -t moussavdb/build-nodejs-$TRAVIS_CPU_ARCH:latest -t moussavdb/build-nodejs-$TRAVIS_CPU_ARCH:build_$TRAVIS_BUILD_NUMBER .
script:
  - docker images moussavdb/build-nodejs
  
after_success:
  - docker login -u="moussavdb" -p="$DOCKER_PASSWORD";
    docker push moussavdb/build-nodejs-$TRAVIS_CPU_ARCH:latest;
    docker push moussavdb/build-nodejs-$TRAVIS_CPU_ARCH:build_$TRAVIS_BUILD_NUMBER;
